version: '2'

services:
  web:
    build: .
    command: honcho start web
    environment:
      - DJANGO_ENV=production
      - PYTHONUNBUFFERED=1
      - DJANGO_LOCAL_SETTINGS=/config/production/local_settings.py
      - DATABASE_HOST=db
      - DATABASE_NAME=vidtrest
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - SENDGRID_USER=
      - SENDGRID_PASSWORD=
    volumes:
      - "./Procfile:/Procfile"
      - "./manage.py:/manage.py"
      - "./requirements.py:/requirements.py"
      - ./vidtrest:/vidtrest
      - ./templates:/templates
      - ./static:/static
      - ./media:/media
      - ./whoosh_index:/whoosh_index
      - ./config:/config
      - ./bower_components:/bower_components
      - ./ansible:/ansible
    ports:
      - "8000:8000"
    links:
      - db
      - redis
      - elasticsearch
    depends_on:
      - db
      - redis
      - elasticsearch
    stdin_open: true
    tty: true

  worker:
    build: .
    command: honcho start worker
    environment:
      - DJANGO_ENV=production
      - PYTHONUNBUFFERED=1
      - DJANGO_LOCAL_SETTINGS=/config/production/local_settings.py
      - DATABASE_HOST=db
      - DATABASE_NAME=vidtrest
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - SENDGRID_USER=
      - SENDGRID_PASSWORD=
    volumes_from:
      - web
    links:
      - db
      - redis
      - elasticsearch
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  db:
    image: library/postgres:9.6.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vidtrest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw

  redis:
    image: library/redis:4.0-alpine

  elasticsearch:
    image: library/elasticsearch:2-alpine  # must be 2 not 5 as haystack is building upgradepath
    volumes:
      - ./search-data:/usr/share/elasticsearch/data:rw

  nginx:
    image: library/nginx:stable-alpine
    ports:
      - "8001:80"
    volumes:
      - ./config/production/nginx:/etc/nginx/conf.d:ro
      - ./static:/static
      - ./media:/media
    links:
      - web

volumes:
  vidtrest:
    driver: local
  postgres-data:
    driver: local
  templates:
    driver: local
  static:
    driver: local
  media:
    driver: local
  whoosh_index:
    driver: local
  config:
    driver: local
  bower_components:
    driver: local
  ansible:
    driver: local
