# Generated by Django 4.2.2 on 2023-06-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vid", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vid",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
