#
# Server
#
server {
    listen 80 default;

    root /var/apps/vidtrest/static;
    index index.html index.htm;

    access_log  /var/log/nginx/vidtrest-production.access.log;
    error_log /var/log/nginx/vidtrest-production.error.log;

    client_max_body_size 4G;

    keepalive_timeout 5;

    location /media {
        add_header 'Access-Control-Allow-Origin' '*';
        access_log off;
        autoindex on;
        #expires 30d;

        alias /var/apps/vidtrest/media;

        location ~ .mp4$ {
                mp4;
                mp4_buffer_size 4M;
                mp4_max_buffer_size 10M;
        }

    }

    location /static {
        add_header 'Access-Control-Allow-Origin' '*';
        access_log off;
        autoindex on;
        #expires 30d;
        alias /var/apps/vidtrest/static;
    }

}