#
# Primary UWSGI server
# for the vidtrest django app
#
upstream vidtrest_app_server {
    server web:8000;
}

#
# Server
#
server {
    listen 80 default;
    server_name localhost;
    client_max_body_size 4G;
    keepalive_timeout 5;

    root /static;
    index index.html index.htm;

    access_log  /var/log/nginx/vidtrest-production.access.log;
    error_log /var/log/nginx/vidtrest-production.error.log;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://vidtrest_app_server;
    }

    # your Django project's static files - amend as required
    location /static {
        access_log off;
        autoindex on;
        expires 5d;
        alias /static;
    }
    location /media {
        access_log off;
        autoindex on;
        expires 5d;
        alias /media;
    }
}
