#
# Primary UWSGI server
# for the vidtrest django app
#
upstream django_app {
    server web:8000;
}

#
# Server
#
server {
    listen 80 default;
    server_name _;

    root /static;
    index index.html index.htm;

    access_log  /var/log/nginx/vidtrest-production.access.log;
    error_log /var/log/nginx/vidtrest-production.error.log;

    client_max_body_size 4G;

    keepalive_timeout 5;

    location / {
      # checks for static file, if not found proxy to app
      try_files $uri @proxy_to_app;
    }

    location @proxy_to_app {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      # enable this if and only if you use HTTPS
      # proxy_set_header X-Forwarded-Proto https;
      proxy_set_header Host $http_host;
      # we don't want nginx trying to do something clever with
      # redirects, we set the Host: header above already.
      proxy_redirect off;
      proxy_pass http://django_app;
    }

    # your Django project's static files - amend as required
    location /static {
        access_log off;
        autoindex on;
        expires 30d;
        alias /static;
    }

    location /media {
        access_log off;
        autoindex on;
        expires 1d;
        alias /media;
    }
}