# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import taggit.managers
import vidtrest.apps.utils
import vidtrest.apps.vid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.FileField(null=True, storage=vidtrest.apps.utils.OverwriteStorage(), upload_to=vidtrest.apps.vid.models._upload_video)),
                ('s3_video', models.FileField(null=True, storage=vidtrest.apps.utils.OverwriteStorage(), upload_to=vidtrest.apps.vid.models._upload_video)),
                ('categories', models.ManyToManyField(to='categories.VideoCat')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='VideoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(blank=True, max_length=24, null=True)),
                ('duration', models.CharField(blank=True, max_length=24, null=True)),
                ('file_size', models.CharField(blank=True, max_length=24, null=True)),
                ('avg_bitrate', models.CharField(blank=True, max_length=24, null=True)),
                ('audio_sample_rate', models.CharField(blank=True, max_length=24, null=True)),
                ('video_frame_rate', models.CharField(blank=True, max_length=24, null=True)),
                ('audio_bits_per_sample', models.CharField(blank=True, max_length=24, null=True)),
                ('track_duration', models.CharField(blank=True, max_length=24, null=True)),
                ('x_resolution', models.CharField(blank=True, max_length=24, null=True)),
                ('y_resolution', models.CharField(blank=True, max_length=24, null=True)),
                ('file_type', models.CharField(blank=True, max_length=24, null=True)),
                ('audio_format', models.CharField(blank=True, max_length=24, null=True)),
                ('compressor_id', models.CharField(blank=True, max_length=24, null=True)),
                ('image_size', models.CharField(blank=True, max_length=24, null=True)),
                ('image_height', models.CharField(blank=True, max_length=24, null=True)),
                ('image_width', models.CharField(blank=True, max_length=24, null=True)),
                ('data', jsonfield.fields.JSONField(default={})),
                ('vid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vid.Vid')),
            ],
        ),
    ]
