# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 13:50
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='video',
            field=s3direct.fields.S3DirectField(null=True),
        ),
    ]
