# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto
import uuid
import vidtrest.apps.vid.models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='vid',
            name='s3_video',
            field=models.FileField(null=True, storage=storages.backends.s3boto.S3BotoStorage(), upload_to=vidtrest.apps.vid.models._upload_video),
        ),
    ]
