# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0002_auto_20160418_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
