# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto
import vidtrest.apps.vid.models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0002_vid_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid',
            name='video',
            field=models.FileField(null=True, storage=storages.backends.s3boto.S3BotoStorage(), upload_to=vidtrest.apps.vid.models._upload_video),
        ),
    ]
