# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import vidtrest.apps.utils
import vidtrest.apps.vid.models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0003_auto_20160409_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default={})),
            ],
        ),
        migrations.RemoveField(
            model_name='vid',
            name='data',
        ),
        migrations.AlterField(
            model_name='vid',
            name='video',
            field=models.FileField(null=True, storage=vidtrest.apps.utils.OverwriteStorage(), upload_to=vidtrest.apps.vid.models._upload_video),
        ),
        migrations.AddField(
            model_name='videometa',
            name='vid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vid.Vid'),
        ),
    ]
