# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import vidtrest.apps.utils
import vidtrest.apps.vid.models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0004_vid_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid',
            name='video',
            field=models.FileField(null=True, storage=vidtrest.apps.utils.OverwriteStorage(), upload_to=vidtrest.apps.vid.models._upload_video, validators=[vidtrest.apps.vid.models._validate_file_extension]),
        ),
    ]
