# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0004_auto_20160409_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
