# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('vid', '0005_auto_20160411_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='categories',
            field=models.ManyToManyField(to='categories.VideoCat'),
        ),
    ]
