# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 12:25
from __future__ import unicode_literals

from django.db import migrations


def migrate_thumbnail_data(apps, schema_editor):
    VideoMeta = apps.get_model("vid", "VideoMeta")

    for meta in VideoMeta.objects.all():
        thumbs_timestamp = meta.data.get('thumbs_timestamp', [])
        thumbs = meta.data.get('thumbs', [])

        for thumb in thumbs:
            thumbs_timestamp.append(0)

        meta.data['thumbs_timestamp'] = thumbs_timestamp
        meta.save(update_fields=['data'])


def un_migrate_thumbnail_data(apps, schema_editor):
    VideoMeta = apps.get_model("vid", "VideoMeta")

    for meta in VideoMeta.objects.all():
        meta.data.pop('thumbs_timestamp', None)
        meta.save(update_fields=['data'])


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0006_auto_20160421_0448'),
    ]

    operations = [
        migrations.RunPython(migrate_thumbnail_data, un_migrate_thumbnail_data),
    ]
