# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0006_vid_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vid',
            name='slug',
        ),
    ]
