# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0007_remove_vid_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometa',
            name='audio_bits_per_sample',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='audio_format',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='audio_sample_rate',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='avg_bitrate',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='compressor_id',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='duration',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='file_size',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='file_type',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='image_height',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='image_size',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='image_width',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='mime_type',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='track_duration',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='video_frame_rate',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='x_resolution',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='videometa',
            name='y_resolution',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
