# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import vidtrest.apps.utils
import vidtrest.apps.vid.models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0007_auto_20160427_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vid',
            options={'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.AlterModelOptions(
            name='videometa',
            options={'verbose_name': 'video metadata', 'verbose_name_plural': 'video metadata'},
        ),
        migrations.RemoveField(
            model_name='vid',
            name='description',
        ),
        migrations.AlterField(
            model_name='vid',
            name='s3_video',
            field=models.FileField(blank=True, max_length=500, null=True, storage=vidtrest.apps.utils.OverwriteStorage(), upload_to=vidtrest.apps.vid.models._upload_video),
        ),
        migrations.AlterField(
            model_name='vid',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, storage=vidtrest.apps.utils.OverwriteStorage(), upload_to=vidtrest.apps.vid.models._upload_video, validators=[vidtrest.apps.vid.models._validate_file_extension]),
        ),
    ]
