# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0008_auto_20160430_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 30, 10, 35, 11, 569733, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vid',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 30, 10, 35, 17, 817688, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
