# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import vidtrest.apps.utils
import vidtrest.apps.vid.models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0009_auto_20160412_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='s3_video',
            field=models.FileField(null=True, storage=vidtrest.apps.utils.OverwriteStorage(), upload_to=vidtrest.apps.vid.models._upload_video),
        ),
    ]
