# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vid', '0009_auto_20160430_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
